# Generated by Django 5.0 on 2023-12-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_magazin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakaz',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='tovars',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='zakaz',
            name='Id_tovara',
        ),
        migrations.AddField(
            model_name='tovars',
            name='Id_tovara',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zakaz',
            name='ID',
            field=models.ManyToManyField(to='internet_magazin.tovars'),
        ),
    ]
