# Generated by Django 5.0 on 2023-12-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_magazin', '0002_alter_zakaz_options_remove_tovars_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovars',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
